### ISSUE TITLE
Wrong natures displaying

### ISSUE THREAD

**Issue by Flametix** [SteveCookTU/sv_raid_lookup#1]
The 7 star Decidueye appeared as Adamant when it was Brave and Samurott appears as Brave when it is Lonely so I believe the nature index being displayed is off by one.
![image](https://user-images.githubusercontent.com/44883711/228991638-e9bd7b96-31fe-42b8-b6f9-472c623c48f6.png)

**Comment by SteveCookTU** [comment]
Was a mix of them using 0 as the index for random (causing the 1 off) as well as a copy paste that was never fixed in `sv_raid_reader`. Should be all set now, thanks for reporting this! 

Closed with [a0b4030](https://github.com/SteveCookTU/sv_raid_lookup/commit/a0b403028e6aa5c4b7f128364614584ed9e99d49)
